name: apn_router
description: A new Appnormal flutter package which provides a custom router with simple page routes.
version: 3.0.0
homepage: https://github.com/appnormal/apn_router

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
