name: apn_router
description: A new Appnormal flutter package which provides a custom router with simple page routes.
version: 1.1.2
homepage: https://github.com/appnormal/apn_router

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
